import { ROLES } from '@/config/constants';

/**
 * Action registry: one place to define semantics for every user-triggered action.
 *
 * Conventions:
 * - actionId: stable, dot-separated (category.verb[.object])
 * - Shift+Click on an ActionButton opens the Action Details panel.
 */
export const ACTIONS = {
  // Navigation
  'nav.goto.dashboard': {
    name: 'Open Dashboard',
    description: 'Navigate to the operations dashboard view.',
    purpose: 'Access high-level fleet overview and KPIs.',
    category: 'navigation',
    functionalImpact: 'No vehicle-side effect; changes operator context only.',
    technicalImpact: 'Client-side route change; may trigger data queries.',
    safetyImpact: 'None (informational navigation).',
    safetyClass: 'none',
    riskLevel: 'low',
    preconditions: [],
    postconditions: ['Dashboard route is active.'],
    failureScenarios: ['Route load fails or API queries fail.'],
    emergencyBehavior: 'No emergency behavior required.',
    dependencies: ['Dashboard route', 'API connectivity (optional)'],
    permissionsRequired: [ROLES.VIEWER, ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    logging: { required: false, auditTrail: false },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Ensure you are viewing the correct operational context.',
    tooltip: 'Go to Dashboard',
    colorSemantics: 'ghost',
    visualPriority: 'normal',
  },

  // Map
  'map.fullscreen.toggle': {
    name: 'Toggle Fullscreen Map',
    description: 'Expand/collapse the live map to fullscreen.',
    purpose: 'Improve situational awareness in monitoring mode.',
    category: 'navigation',
    functionalImpact: 'No vehicle-side effect; changes display layout.',
    technicalImpact: 'UI state update; map reflow.',
    safetyImpact: 'Low; helps monitoring but can hide other panels.',
    safetyClass: 'advisory',
    riskLevel: 'low',
    preconditions: [],
    postconditions: ['Map layout toggled.'],
    failureScenarios: ['Browser performance issues on low-end devices.'],
    emergencyBehavior: 'Exit fullscreen to access other controls if needed.',
    dependencies: ['Leaflet map'],
    permissionsRequired: [ROLES.VIEWER, ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    logging: { required: false, auditTrail: false },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Maintain awareness of other alerts while fullscreen.',
    tooltip: 'Fullscreen',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },

  // Fleet / commands
  'control.command.arm': {
    name: 'ARM Vehicle',
    description: 'Arms the vehicle motors/actuators to enable takeoff or movement.',
    purpose: 'Transition vehicle from safe state to ready-to-actuate state.',
    category: 'control',
    functionalImpact: 'Vehicle becomes capable of producing thrust/motion.',
    technicalImpact: 'Command published to control channel; autopilot state changes to ARMED.',
    safetyImpact: 'High: may enable unexpected motion if area is not clear.',
    safetyClass: 'flight_safety',
    riskLevel: 'high',
    preconditions: ['Vehicle connected', 'Operator has line-of-sight or equivalent monitoring', 'Area is clear'],
    postconditions: ['Vehicle reports ARMED state'],
    failureScenarios: ['Command rejected by autopilot', 'Safety checks fail', 'Link loss'],
    emergencyBehavior: 'If unsafe, DISARM or E-STOP immediately.',
    dependencies: ['MQTT/WebSocket link', 'Autopilot safety checks'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: true, style: 'danger', prompt: 'Arm the vehicle? Ensure the area is clear.' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Verify environment safety and correct vehicle selection.',
    tooltip: 'ARM (enables actuation)',
    safetyLabel: 'Flight Safety',
    riskIndicator: 'HIGH',
    colorSemantics: 'success',
    visualPriority: 'high',
  },
  'control.command.disarm': {
    name: 'DISARM Vehicle',
    description: 'Disarms the vehicle to disable motors/actuators.',
    purpose: 'Return vehicle to safe non-actuating state.',
    category: 'safety',
    functionalImpact: 'Vehicle cannot produce thrust/motion.',
    technicalImpact: 'Command published; autopilot transitions to DISARMED.',
    safetyImpact: 'Medium: may terminate flight if used improperly.',
    safetyClass: 'flight_safety',
    riskLevel: 'high',
    preconditions: ['Vehicle connected', 'Operator understands current flight state'],
    postconditions: ['Vehicle reports DISARMED state'],
    failureScenarios: ['Command rejected', 'Link loss'],
    emergencyBehavior: 'If vehicle is on ground and unsafe, prefer E-STOP.',
    dependencies: ['MQTT/WebSocket link'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: true, style: 'danger', prompt: 'Disarm the vehicle?' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Use only when safe; avoid mid-flight unless required.',
    tooltip: 'DISARM (disable actuation)',
    safetyLabel: 'Flight Safety',
    riskIndicator: 'HIGH',
    colorSemantics: 'danger',
    visualPriority: 'urgent',
  },
  'control.command.takeoff': {
    name: 'Takeoff',
    description: 'Initiate autonomous takeoff to a predefined altitude.',
    purpose: 'Start flight safely using autopilot takeoff logic.',
    category: 'control',
    functionalImpact: 'Vehicle lifts off and climbs.',
    technicalImpact: 'Command sent; autopilot executes takeoff sequence.',
    safetyImpact: 'High: vehicle will move and climb.',
    safetyClass: 'flight_safety',
    riskLevel: 'high',
    preconditions: ['Vehicle armed', 'GPS/position adequate', 'Area clear'],
    postconditions: ['Vehicle transitions to takeoff/flight mode'],
    failureScenarios: ['Takeoff rejected', 'Altitude hold failure', 'Link loss'],
    emergencyBehavior: 'LAND/RTL/E-STOP depending on severity.',
    dependencies: ['Autopilot mode support', 'Telemetry link'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'partially_reversible',
    confirmation: { required: true, style: 'danger', prompt: 'Takeoff now?' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Confirm airspace clearance and correct vehicle.',
    tooltip: 'Takeoff',
    safetyLabel: 'Flight Safety',
    riskIndicator: 'HIGH',
    colorSemantics: 'primary',
    visualPriority: 'high',
  },
  'control.command.land': {
    name: 'Land',
    description: 'Initiate landing at current location (or landing target).',
    purpose: 'Safely terminate flight.',
    category: 'control',
    functionalImpact: 'Vehicle descends and lands.',
    technicalImpact: 'Command sent; autopilot executes landing logic.',
    safetyImpact: 'High: vehicle descends; may impact obstacles/people if misused.',
    safetyClass: 'flight_safety',
    riskLevel: 'high',
    preconditions: ['Vehicle in flight', 'Landing zone is safe'],
    postconditions: ['Vehicle transitions to landing'],
    failureScenarios: ['Landing rejected', 'Obstacle collision risk'],
    emergencyBehavior: 'E-STOP only if required and safe.',
    dependencies: ['Autopilot landing support'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'partially_reversible',
    confirmation: { required: true, style: 'standard', prompt: 'Land the vehicle?' },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Ensure landing area is clear.',
    tooltip: 'Land',
    safetyLabel: 'Flight Safety',
    riskIndicator: 'HIGH',
    colorSemantics: 'secondary',
    visualPriority: 'high',
  },
  'control.command.rtl': {
    name: 'Return To Launch (RTL)',
    description: 'Command vehicle to return to launch/home position and land.',
    purpose: 'Recover vehicle safely when mission is aborted or link quality degrades.',
    category: 'safety',
    functionalImpact: 'Vehicle navigates home; may climb/turn.',
    technicalImpact: 'Command sent; autopilot enters RTL mode.',
    safetyImpact: 'High: vehicle changes trajectory autonomously.',
    safetyClass: 'flight_safety',
    riskLevel: 'high',
    preconditions: ['Home position set', 'GPS adequate'],
    postconditions: ['Vehicle enters RTL mode'],
    failureScenarios: ['Home not set', 'GPS degraded'],
    emergencyBehavior: 'If RTL unsafe, switch to HOLD or LAND depending on environment.',
    dependencies: ['Autopilot RTL support'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'partially_reversible',
    confirmation: { required: true, style: 'standard', prompt: 'Initiate RTL?' },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Confirm RTL path is safe and airspace is clear.',
    tooltip: 'RTL',
    safetyLabel: 'Safety',
    riskIndicator: 'HIGH',
    colorSemantics: 'warning',
    visualPriority: 'high',
  },
  'control.command.hold': {
    name: 'Hold (Loiter)',
    description: 'Command vehicle to hold position / loiter safely.',
    purpose: 'Stabilize flight and pause movement while assessing conditions.',
    category: 'safety',
    functionalImpact: 'Vehicle attempts to maintain position/altitude.',
    technicalImpact: 'Command sent; autopilot enters HOLD/LOITER mode.',
    safetyImpact: 'Medium: helps stop motion; may be unsafe in strong wind/low altitude.',
    safetyClass: 'flight_safety',
    riskLevel: 'medium',
    preconditions: ['Vehicle connected'],
    postconditions: ['Vehicle enters hold/loiter mode'],
    failureScenarios: ['Mode change rejected', 'GPS degraded', 'Link loss'],
    emergencyBehavior: 'If hold is unsafe, LAND/RTL depending on environment.',
    dependencies: ['Autopilot mode support'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Monitor drift and verify safe altitude/airspace.',
    tooltip: 'Hold position',
    safetyLabel: 'Flight Safety',
    riskIndicator: 'MEDIUM',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'control.command.emergency_stop': {
    name: 'Emergency Stop',
    description: 'Immediately stop vehicle actuation (failsafe / kill).',
    purpose: 'Mitigate imminent hazard to life/property.',
    category: 'emergency',
    functionalImpact: 'Vehicle may drop or stop abruptly depending on platform.',
    technicalImpact: 'Highest-priority command; may bypass normal control logic.',
    safetyImpact: 'Critical: may prevent harm but can also cause crash.',
    safetyClass: 'life_safety',
    riskLevel: 'critical',
    preconditions: ['Imminent hazard exists'],
    postconditions: ['Vehicle attempts immediate stop/kill'],
    failureScenarios: ['Command not received', 'Actuator failure'],
    emergencyBehavior: 'This action is the emergency behavior.',
    dependencies: ['Emergency channel availability'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'irreversible',
    confirmation: { required: true, style: 'danger', prompt: 'EMERGENCY STOP? Use only to prevent harm.' },
    logging: { required: true, level: 'error', auditTrail: true, includePayload: true },
    realtimeEffect: 'vehicle',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Only use to prevent harm; report and document incident.',
    tooltip: 'Emergency Stop (kill)',
    safetyLabel: 'Life Safety',
    riskIndicator: 'CRITICAL',
    colorSemantics: 'danger',
    visualPriority: 'urgent',
  },

  // Mission planning
  'mission.create': {
    name: 'Create Mission',
    description: 'Create a new mission container (draft) in the system.',
    purpose: 'Start a new mission planning workflow.',
    category: 'mission',
    functionalImpact: 'Creates a new draft mission record.',
    technicalImpact: 'Client state update and/or API create request.',
    safetyImpact: 'Low: planning-stage action; operational risk depends on later execution.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['User authenticated'],
    postconditions: ['Draft mission exists'],
    failureScenarios: ['API failure', 'Validation failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    logging: { required: true, level: 'info', auditTrail: true, includePayload: false },
    realtimeEffect: 'local',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Name missions clearly to avoid later confusion.',
    tooltip: 'Create new mission',
    colorSemantics: 'primary',
  },
  'mission.load': {
    name: 'Load Mission Into Planner',
    description: 'Load the selected mission into the editor and map preview.',
    purpose: 'Review and modify an existing mission safely.',
    category: 'mission',
    functionalImpact: 'Updates local planner state to selected mission.',
    technicalImpact: 'API read to fetch mission details and waypoints.',
    safetyImpact: 'Low: planning-stage action only.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Mission exists'],
    postconditions: ['Planner loads mission waypoints'],
    failureScenarios: ['API failure', 'Mission not found'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: false },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Confirm correct mission and version are selected.',
    tooltip: 'Load mission',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'mission.update': {
    name: 'Update Mission',
    description: 'Save edits to the selected mission metadata and parameters.',
    purpose: 'Keep mission definition accurate and current.',
    category: 'mission',
    functionalImpact: 'Updates mission record in the database.',
    technicalImpact: 'API update request.',
    safetyImpact: 'Low: planning-stage change; operational impact depends on later execution.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Mission selected'],
    postconditions: ['Mission metadata updated'],
    failureScenarios: ['Validation failure', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Review parameters before saving changes.',
    tooltip: 'Update mission',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'mission.delete': {
    name: 'Delete Mission',
    description: 'Remove a mission from the system.',
    purpose: 'Clean up obsolete or invalid mission definitions.',
    category: 'mission',
    functionalImpact: 'Deletes mission record and associated data.',
    technicalImpact: 'API delete request.',
    safetyImpact: 'Medium: can remove active or planned missions if misused.',
    safetyClass: 'operational',
    riskLevel: 'medium',
    preconditions: ['Mission selected', 'Mission not executing'],
    postconditions: ['Mission removed'],
    failureScenarios: ['Deletion blocked by server policy', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'irreversible',
    confirmation: { required: true, style: 'danger', prompt: 'Delete this mission? This cannot be undone.' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Confirm mission is not required for operations.',
    tooltip: 'Delete mission',
    colorSemantics: 'danger',
    visualPriority: 'high',
  },
  'mission.duplicate': {
    name: 'Duplicate Mission',
    description: 'Create a new mission by copying the selected mission.',
    purpose: 'Speed up mission creation based on known-good templates.',
    category: 'mission',
    functionalImpact: 'Creates a new mission with copied waypoints.',
    technicalImpact: 'API create request with copied payload.',
    safetyImpact: 'Low: planning-stage action.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Mission selected'],
    postconditions: ['New mission created'],
    failureScenarios: ['API failure', 'Validation failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'none',
    operatorResponsibility: 'Ensure copied mission parameters are updated.',
    tooltip: 'Duplicate mission',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },

  // Entity management (vehicles)
  'entity.vehicle.create': {
    name: 'Register Vehicle',
    description: 'Create a new vehicle entity in the registry.',
    purpose: 'Add drones/robots for management, telemetry, and missions.',
    category: 'fleet',
    functionalImpact: 'Creates a new vehicle record.',
    technicalImpact: 'API create request to vehicle registry.',
    safetyImpact: 'Low: administrative action only.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['User authenticated'],
    postconditions: ['Vehicle record created'],
    failureScenarios: ['Validation failure', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Fleet service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Ensure identity and type are correct.',
    tooltip: 'Add vehicle',
    colorSemantics: 'primary',
    visualPriority: 'normal',
  },
  'entity.vehicle.update': {
    name: 'Update Vehicle',
    description: 'Edit vehicle metadata and registry fields.',
    purpose: 'Keep the registry accurate and operational.',
    category: 'fleet',
    functionalImpact: 'Updates vehicle record.',
    technicalImpact: 'API update request.',
    safetyImpact: 'Low: administrative action only.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Vehicle exists'],
    postconditions: ['Vehicle record updated'],
    failureScenarios: ['Validation failure', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Fleet service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Verify identifiers before saving.',
    tooltip: 'Edit vehicle',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'entity.vehicle.delete': {
    name: 'Delete Vehicle',
    description: 'Remove a vehicle from the registry.',
    purpose: 'Decommission or clean up obsolete entities.',
    category: 'fleet',
    functionalImpact: 'Deletes vehicle record.',
    technicalImpact: 'API delete request.',
    safetyImpact: 'Medium: can remove an active vehicle if misused.',
    safetyClass: 'operational',
    riskLevel: 'medium',
    preconditions: ['Vehicle exists', 'Vehicle not in active mission'],
    postconditions: ['Vehicle record removed'],
    failureScenarios: ['Deletion blocked by policy', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Fleet service'],
    permissionsRequired: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'irreversible',
    confirmation: { required: true, style: 'danger', prompt: 'Delete this vehicle? This cannot be undone.' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Confirm vehicle is decommissioned.',
    tooltip: 'Delete vehicle',
    colorSemantics: 'danger',
    visualPriority: 'high',
  },
  'entity.fleet.create': {
    name: 'Create Fleet',
    description: 'Create a new fleet to group vehicles and missions.',
    purpose: 'Organize vehicles and control visibility.',
    category: 'fleet',
    functionalImpact: 'Adds a new fleet record.',
    technicalImpact: 'API create request to fleet service.',
    safetyImpact: 'Low: administrative action only.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Admin role'],
    postconditions: ['Fleet created'],
    failureScenarios: ['Validation failure', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Fleet service'],
    permissionsRequired: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Ensure fleet naming matches org structure.',
    tooltip: 'Add fleet',
    colorSemantics: 'primary',
    visualPriority: 'normal',
  },
  'entity.fleet.update': {
    name: 'Update Fleet',
    description: 'Edit fleet name or description.',
    purpose: 'Keep fleet metadata current.',
    category: 'fleet',
    functionalImpact: 'Updates a fleet record.',
    technicalImpact: 'API update request to fleet service.',
    safetyImpact: 'Low.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Fleet exists', 'Admin role'],
    postconditions: ['Fleet updated'],
    failureScenarios: ['Validation failure', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Fleet service'],
    permissionsRequired: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Verify fleet metadata before saving.',
    tooltip: 'Edit fleet',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'entity.fleet.delete': {
    name: 'Delete Fleet',
    description: 'Remove a fleet from the registry.',
    purpose: 'Clean up unused fleets.',
    category: 'fleet',
    functionalImpact: 'Deletes a fleet record.',
    technicalImpact: 'API delete request to fleet service.',
    safetyImpact: 'Medium: may affect assignments.',
    safetyClass: 'operational',
    riskLevel: 'medium',
    preconditions: ['Fleet empty', 'Admin role'],
    postconditions: ['Fleet removed'],
    failureScenarios: ['Fleet not empty', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Fleet service'],
    permissionsRequired: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'irreversible',
    confirmation: { required: true, style: 'danger', prompt: 'Delete this fleet? This cannot be undone.' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Ensure no vehicles are assigned.',
    tooltip: 'Delete fleet',
    colorSemantics: 'danger',
    visualPriority: 'high',
  },
  'entity.fleet.assign_user': {
    name: 'Assign Fleet Members',
    description: 'Assign users to a fleet for scoped visibility.',
    purpose: 'Control fleet access by role.',
    category: 'fleet',
    functionalImpact: 'Updates fleet-user mappings.',
    technicalImpact: 'API assignment request.',
    safetyImpact: 'Low.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Admin role'],
    postconditions: ['Users assigned to fleet'],
    failureScenarios: ['API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Auth service', 'Fleet service'],
    permissionsRequired: [ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'local',
    missionEffect: 'none',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Assign only authorized staff.',
    tooltip: 'Manage fleet members',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'mission.assign': {
    name: 'Assign Mission',
    description: 'Bind a mission to one or more vehicles.',
    purpose: 'Schedule mission execution on specific vehicles.',
    category: 'mission',
    functionalImpact: 'Creates mission assignments.',
    technicalImpact: 'API assignment request + real-time update.',
    safetyImpact: 'Medium: affects execution plan.',
    safetyClass: 'operational',
    riskLevel: 'medium',
    preconditions: ['Mission exists', 'Vehicle available'],
    postconditions: ['Mission assigned'],
    failureScenarios: ['Vehicle unavailable', 'API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service', 'Fleet service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'real-time',
    missionEffect: 'mission',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Confirm vehicle readiness before assignment.',
    tooltip: 'Assign mission to vehicles',
    colorSemantics: 'primary',
    visualPriority: 'normal',
  },
  'mission.unassign': {
    name: 'Unassign Mission',
    description: 'Remove mission assignments from vehicles.',
    purpose: 'Clear mission bindings.',
    category: 'mission',
    functionalImpact: 'Deactivates mission assignments.',
    technicalImpact: 'API unassignment request.',
    safetyImpact: 'Low.',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Mission assigned'],
    postconditions: ['Mission unassigned'],
    failureScenarios: ['API failure'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: true },
    realtimeEffect: 'real-time',
    missionEffect: 'mission',
    fleetEffect: 'fleet',
    operatorResponsibility: 'Confirm mission can be safely removed.',
    tooltip: 'Unassign mission',
    colorSemantics: 'secondary',
    visualPriority: 'normal',
  },
  'mission.draft.clear': {
    name: 'Clear Draft Waypoints',
    description: 'Remove all waypoints from the current draft plan.',
    purpose: 'Reset planning workspace.',
    category: 'mission',
    functionalImpact: 'Draft plan becomes empty.',
    technicalImpact: 'Client state update.',
    safetyImpact: 'Low.',
    safetyClass: 'none',
    riskLevel: 'low',
    preconditions: [],
    postconditions: ['Draft waypoints cleared'],
    failureScenarios: ['None (local state)'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission store'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: true, style: 'standard', prompt: 'Clear all draft waypoints?' },
    logging: { required: true, level: 'info', auditTrail: true },
    realtimeEffect: 'local',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Ensure you don\'t discard an unsaved plan.',
    tooltip: 'Clear waypoints',
    colorSemantics: 'ghost',
  },
  'mission.draft.save': {
    name: 'Save Draft Mission',
    description: 'Save the current mission draft to the backend.',
    purpose: 'Persist mission planning work for later validation and upload.',
    category: 'mission',
    functionalImpact: 'Draft becomes persisted and shareable across sessions.',
    technicalImpact: 'API update request; stores waypoints/graph in DB.',
    safetyImpact: 'Low (planning stage).',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Draft has at least one waypoint'],
    postconditions: ['Draft saved'],
    failureScenarios: ['API failure', 'Validation error'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission service'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    logging: { required: true, level: 'info', auditTrail: true },
    realtimeEffect: 'system',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Save before switching vehicles or uploading.',
    tooltip: 'Save',
    colorSemantics: 'secondary',
  },
  'mission.waypoint.remove': {
    name: 'Remove Waypoint',
    description: 'Remove a waypoint from the draft plan.',
    purpose: 'Edit mission route safely before upload.',
    category: 'mission',
    functionalImpact: 'Waypoint deleted from draft.',
    technicalImpact: 'Client state update.',
    safetyImpact: 'Low (planning).',
    safetyClass: 'operational',
    riskLevel: 'low',
    preconditions: ['Waypoint exists'],
    postconditions: ['Waypoint removed; sequence reindexed'],
    failureScenarios: ['None (local state)'],
    emergencyBehavior: 'N/A',
    dependencies: ['Mission store'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true },
    realtimeEffect: 'local',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Confirm you are editing the intended waypoint.',
    tooltip: 'Remove waypoint',
    colorSemantics: 'ghost',
  },
  'mission.waypoint.add': {
    name: 'Add Waypoint',
    description: 'Adds a waypoint to the draft mission plan at the selected location.',
    purpose: 'Build a mission route for autonomous navigation.',
    category: 'mission',
    functionalImpact: 'Edits mission draft only (no immediate vehicle motion).',
    technicalImpact: 'Client state update; may be saved to backend.',
    safetyImpact: 'Low during planning; incorrect planning increases later operational risk.',
    safetyClass: 'operational',
    riskLevel: 'medium',
    preconditions: ['Operator has correct map context (area/coordinate system)'],
    postconditions: ['Draft includes a new waypoint'],
    failureScenarios: ['Invalid coordinates', 'State not saved'],
    emergencyBehavior: 'N/A (planning).',
    dependencies: ['Mission store'],
    permissionsRequired: [ROLES.OPERATOR, ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'reversible',
    confirmation: { required: false },
    logging: { required: true, level: 'info', auditTrail: true, includePayload: false },
    realtimeEffect: 'local',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Ensure waypoint does not violate airspace/geofence.',
    tooltip: 'Add waypoint',
    safetyLabel: 'Operational',
    riskIndicator: 'MEDIUM',
    colorSemantics: 'primary',
    visualPriority: 'normal',
  },
  'mission.upload': {
    name: 'Upload Mission',
    description: 'Uploads the planned mission to a selected vehicle.',
    purpose: 'Transfer mission plan to edge agent/autopilot.',
    category: 'mission',
    functionalImpact: 'Vehicle receives new mission plan; may become ready to execute.',
    technicalImpact: 'API call then MQTT mission upload workflow.',
    safetyImpact: 'High: wrong mission/vehicle can cause unsafe operation.',
    safetyClass: 'flight_safety',
    riskLevel: 'high',
    preconditions: ['Mission validated', 'Correct vehicle selected', 'Vehicle link available'],
    postconditions: ['Vehicle acknowledges mission received'],
    failureScenarios: ['Upload timeout', 'Edge agent offline', 'Autopilot rejects plan'],
    emergencyBehavior: 'Abort upload and keep vehicle in HOLD/SAFE mode.',
    dependencies: ['API', 'MQTT broker', 'Edge agent'],
    permissionsRequired: [ROLES.PILOT, ROLES.ADMIN, ROLES.SUPER_ADMIN],
    reversible: 'partially_reversible',
    confirmation: { required: true, style: 'standard', prompt: 'Upload mission to vehicle?' },
    logging: { required: true, level: 'warning', auditTrail: true, includePayload: true },
    realtimeEffect: 'system',
    missionEffect: 'mission',
    fleetEffect: 'none',
    operatorResponsibility: 'Verify mission safety and vehicle assignment before upload.',
    tooltip: 'Upload mission',
    safetyLabel: 'Flight Safety',
    riskIndicator: 'HIGH',
    colorSemantics: 'primary',
    visualPriority: 'high',
  },
};

export function getActionMeta(actionId) {
  return ACTIONS[actionId] || null;
}
